### ISSUE TITLE
More listening option

### ISSUE THREAD

**Issue by felixwidjaja** [FinndropStudios/GifRocket#13]
Hi guys, great plugin. Superb. Thank you.

I was wondering: Is there any option to "Listen to all the private channel" also?

**Comment by royalaid** [comment]
I think this is an issue with how rocketchat handles integrations. You might want to file an issue asking there.

**Comment by manuelbachl** [comment]
hi there, as @royalaid mentioned, this is an issue related to rocket chats own behaviour. There's no way to "fix" this inside an integration
