### ISSUE TITLE
not working for 0.40.0 to 0.42.0 

### ISSUE THREAD

**Issue by rrepolona** [FinndropStudios/GifRocket#14]
the giphy webhook is not working on this versions of rocket chat (0.40.0 to 0.42.0)
but working on the early versions.

**Comment by Flitterkill** [comment]
Have you made sure to change the call from /gif to !gif?

Just updated my 0.25 to 0.45 tonight and saw that gifrocket wasn't working anymore.

Noticed the calls had changed in the 6 months since I last looked, change the slashes to ! and worked like a charm.

**Comment by rrepolona** [comment]
yes, im using !gif 

this is the screenshot how i call giphy integration from a public channel
[https://i.imgur.com/AFmtOjb.png](url)

and this is my setup using outgoing webhook
[https://i.imgur.com/qIh2Pbh.png](url)

also check logs, but seems no information about the error. i use this on much earlier version and its working fine. thanks

**Comment by Flitterkill** [comment]
What's your rocket chat address? Be easier to discuss there

**Comment by rrepolona** [comment]
Hi @Flitterkill 

sorry, currently our rocket chat service is private. i will try using this version 0.45.
thanks for your help

**Comment by rrepolona** [comment]
Hi @Flitterkill 

after some updates and redo of configuration, finally the giphy work. 
i'm not really sure what happens. hehe. thanks again
