### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by elfeffe** [FinndropStudios/GifRocket#15]
Clone this repo where?
I'm using Ubuntu 16.04 and Snap installation (recommended by Rocket)

**Comment by jknsware** [comment]
There's really nothing to clone.  Follow the instructions in [README.md](https://github.com/FinndropStudios/GifRocket/blob/master/README.md.) You'll use the [GifRocket.js](https://github.com/FinndropStudios/GifRocket/blob/master/GifRocket.js) file to paste into Rocket.Chat > Administration > Integration

**Comment by elfeffe** [comment]
Thank you for update the Readme. it was a bit confuising.

**Comment by forresthopkinsa** [comment]
That file doesn't exist anymore, though. And the new `GifRocketApp.ts` is not a self-contained script.

**Comment by forresthopkinsa** [comment]
Okay, I've found it in the legacy directory. Docs should definitely be updated.
