### ISSUE TITLE
Random Gif not working... (And I have the fix)

### ISSUE THREAD

**Issue by kobadg** [FinndropStudios/GifRocket#19]
The issue is line 10, the + ' '; actually prevents the random from happening..

`const trigger = request.data.trigger_word.toLowerCase();`

**Comment by manuelbachl** [comment]
Thank you for this solution. I've implemented this fix:
https://github.com/FinndropStudios/GifRocket/commit/6b1e65b14039499e2c27f5afd0d88916134c8c5f#diff-1afb5d8250b8bd46b198a8298d7fa6ee

Would be great if you probably could provide some feedback if it works as expected (have no chance to test atm - no time here :-1: )

**Comment by kobadg** [comment]
That is literally what I have in my chat server running the GIF program. (And I can verify that it does work as intended. If someone else would like to test it, then that works as well, but it does work for me.)
