### ISSUE TITLE
Documentation of Installation

### ISSUE THREAD

**Issue by saschafoerster** [FinndropStudios/GifRocket#23]
I really would like to install this, but I can't understand the installation notes. Where do I need to unzip? Is it an app? Or do I need to install something with docker-compose? It as all unclear. :) Thanks for helping me!

**Comment by saschafoerster** [comment]
Okay, took me some time, to understand it is an "webhook" with script, so there is no "installation" just copy and paste of text.

**Comment by forresthopkinsa** [comment]
What text are you copying and pasting? I can't find `gifrocket.js`.
