### ISSUE TITLE
Error after setup.

### ISSUE THREAD

**Issue by SuperKaioken** [FinndropStudios/GifRocket#24]
Error received after using the !gif random in a public channel.  Other phrases don't work either.

I20181018-11:07:23.187(-5) Exception in callback of async function: TypeError: Cannot read property 'statusCode' of null     at packages/rocketchat_integrations/server/triggers.coffee:211:25     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)

**Comment by SuperKaioken** [comment]
Running version 0.38.0

**Comment by lorek123** [comment]
0.38 is pretty old version of rocketchat, maybe try to update it first ;)

**Comment by SuperKaioken** [comment]
Will do.
