### ISSUE TITLE
Needing Better Integration Instructions

### ISSUE THREAD

**Issue by EricPonvelle** [FinndropStudios/GifRocket#3]
Hello,

I am trying to add this to my Rocket Chat instance. Where exactly do I extract the files? I attempted to add them to the package folder and activate them via Meteor (as I have with other packages, and that didn't work.

Please update the documentation to explain where to place the files.

**Comment by manuelbachl** [comment]
Hi there, since there is no stable "market-place" für integrations you need to add the integration as mentioned in readme. Where exactly you've got questions? Just let me know, I'll update the manual asap

**Comment by EricPonvelle** [comment]
Hey, thanks for the reply!

So, in the readme, you have:

> Download code
> 
> Download source from here.
> Unzip Sources. 

Where exactly am I unzipping my sources? Packages? The root?

I can't get past this step just because I am unsure about the integration before even getting to the admin stuff.

**Comment by manuelbachl** [comment]
Ahhh, now i got your point. Ok, since you would just copy the script from GifRocket.js, it's quite equal where to extract the files. Just download them and extract in your download folder. Or just forget about downloading and open the GifRocket.js on github and click on "Raw". There you could copy the needed script aswell ;-)

**Comment by EricPonvelle** [comment]
I should caveat that I am no developer, so I am coming at this more from a documentation standard/perspective.

To clarify, I just download and extract the sources anywhere. Then, I do the integration via RocketChat as an admin? It's not actually going *inside* of my RocketChat instance?

I apologize if these questions are dumb.

**Comment by manuelbachl** [comment]
There are NO dumb questions ;-)
But yes, you're right. You need to be logged in into your Rocket.Chat instance as an admin and then just follow these steps:
https://rocket.chat/docs/administrator-guides/integrations/
the contents from inside GifRocket.js will be pastet into the field `script`

**Comment by EricPonvelle** [comment]
Simple enough!

I seem to be getting internal errors whenever I try it as an outgoing web
hook, but nothing happens if I do it as incoming. It’s supposed to be
outgoing right?

**Comment by manuelbachl** [comment]
yes, outgoing is correct. You followed all the instructions in the GifRocket manual?

**Comment by manuelbachl** [comment]
seems to be the same as here #4 - got into the Dev-Team to find out whats the problem

**Comment by EricPonvelle** [comment]
Cool! Thanks for looking into this. I'll close this issue to consolidate since the problem is the same.

**Comment by manuelbachl** [comment]
Got Feedback from Dev-team on this:

that issue was fixed by https://github.com/RocketChat/Rocket.Chat/pull/3275

You need to update to a more recent version of rocket.chat to get the fix

**Comment by EricPonvelle** [comment]
Perfect! I’ll do that now.

**Comment by manuelbachl** [comment]
Ok, please let me know if this issue is fixed ;-)
