### ISSUE TITLE
Internal server error on adding webhook

### ISSUE THREAD

**Issue by ramses2000** [FinndropStudios/GifRocket#4]
Hello! I tried to add webhook on new rocket.chat 0.31.0 installation, but after press "Save" button I see error "Internal server error". Rocket.chat log: 
`I20160601-16:40:38.693(3) Exception while invoking method 'addOutgoingIntegration' TypeError: Cannot call method 'split' of undefined     at [object Object].Meteor.methods.addOutgoingIntegration (packages/rocketchat_integrations/server/methods/outgoing/addOutgoingIntegration.coffee:26:40)     at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26)     at maybeAuditArgumentChecks (livedata_server.js:1698:12)     at livedata_server.js:708:19     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at livedata_server.js:706:40     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at livedata_server.js:704:46     at tryCallTwo (/data/Rocket.Chat/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)     at doResolve (/data/Rocket.Chat/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13) `

What am I doing wrong? File GifRocket.js is latest version (downloaded today). Sorry for my bad english :-[

**Comment by manuelbachl** [comment]
ok, have to check this with Rocket.Chat Dev-Team since the script hasent changed since few weeks and worked properly for a while. Seems that this is an issue related to Rocket.Chat
I'll get back here whe I've got news

**Comment by manuelbachl** [comment]
Got Feedback from Dev-team on this:

that issue was fixed by https://github.com/RocketChat/Rocket.Chat/pull/3275

You need to update to a more recent version of rocket.chat to get the fix

**Comment by ramses2000** [comment]
Thanks, now it works!

**Comment by manuelbachl** [comment]
ok fine! thanks for your feedback
