### ISSUE TITLE
Commands not displayed in chat command list, but works.

### ISSUE THREAD

**Issue by ramses2000** [FinndropStudios/GifRocket#5]
Hello. After adding webhook, giphy commands ("/gif" and "/sticker") works, but not displayed in chat command list:
![commands_rch](https://cloud.githubusercontent.com/assets/19343411/15737251/ced99626-28ad-11e6-8108-828a6e600b14.PNG)
Is it feature of GifRocket or Rocket.Chat? My R.C fresh installation version is 0.32.0, and no errors in logs.

**Comment by manuelbachl** [comment]
Oh this commands list is new to me - Don't know wether there is a way to get listet there. But I think I'll get an answer on this from devs soon

**Comment by manuelbachl** [comment]
This is an "issue" in Rocket.Chat itself. Rocket.Chat just displays the built in commands atm. But there are plans in building an API for listing commands from Webhook.

> diego.sampaio Rocket.Chat Team 13:53  durch  
 
yes @manuelbachl .. at the moment they are slash commands.. but in the future we plan to provide an API to populate them from webhooks
