### ISSUE TITLE
Bad sources link

### ISSUE THREAD

**Issue by killinterpol** [FinndropStudios/GifRocket#8]
Following your link:
https://git.finndrop-office.de/plugins/servlet/archive/projects/FDS/repos/gifrocket?at=refs%2Fheads%2Fmaster

Results in:
502 Bad Gateway - nginx

Just a suggestion - Any reason not to host source here on github?

**Comment by manuelbachl** [comment]
Hi There, sorry for late Reply (Notification System of github seems a little buggy...
The link in the readme file is an old one - our fault. Forgot to update the readme.md
Just use the regular download link provided by github in the uper right corner ;-)
We'll try to update asap.
